# Generated by Django 5.2.5 on 2025-08-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamburgueria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='nome',
            field=models.CharField(default='sem nome', max_length=100),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pagamento',
            field=models.CharField(choices=[('pix', 'pix'), ('cartao', 'cartao'), ('dinheiro', 'dinheiro')], max_length=20),
        ),
    ]
