# Generated by Django 5.2.5 on 2025-08-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('itens', models.JSONField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pagamento', models.CharField(choices=[('pix', 'pix'), ('cartao', 'cartao'), ('concluido', 'concluido')], max_length=20)),
                ('endereco', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'pendente'), ('fazendo', 'fazendo'), ('rota_entrega', 'rota de entrega'), ('concluido', 'concluido')], max_length=20)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
