# Generated by Django 5.2.5 on 2025-08-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedidos_nome_alter_pedidos_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
