# Generated by Django 5.2.5 on 2025-08-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_alter_pedidos_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='status',
            field=models.CharField(choices=[('pendente', 'pendente'), ('fazendo', 'fazendo'), ('rota_entrega', 'rota de entrega'), ('concluido', 'concluido')], default='pendente', max_length=20),
        ),
    ]
